# -*- coding: utf-8 -*-
"""Creatingnewlayers.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7PM4-3QuUU2rlf_W7N5SUO-Kux5mYxp
"""

!pip install geopandas

#Start by importing necessary modules
import geopandas as gpd
from shapely.geometry import Point, Polygon
from pyproj import CRS

# Let’s create an empty GeoDataFrame
newdata = gpd.GeoDataFrame()

print(newdata)

# Create a new column called 'geometry' to the GeoDataFrame
newdata['geometry'] = None

print(newdata)

# Coordinates of the Helsinki Senate square in decimal degrees
coordinates = [(24.950899, 60.169158), (24.953492, 60.169158), (24.953510, 60.170104), (24.950958, 60.169990)]

# Create a Shapely polygon from the coodinare-tuple list
poly = Polygon(coordinates)

# Check the polygon
print(poly)

# Insert the polygon into geometry -column at row 0
newdata.at[0, 'geometry'] = poly

# Let´s see what we have now
print(newdata)

# Add a new column and insert data
newdata.at[0, 'location'] = 'Senaatinori'

# Let´s check the data
print(newdata)

# Verifict the crs of the data
print(newdata.crs)

# Set the GeoDataFrame's coordinate system to WGS84 (i.e. epsg code 4326)
newdata.crs = CRS.from_epsg(4326).to_wkt()

print(newdata.crs)

# Determine the output path for the Shapefile
output = "/content/drive/MyDrive/Colab/L2_data/Senaatintori.shp"

# Write the data into that Shapefile
newdata.to_file(output)

newdata

# Plot the data
newdata.at[0, "geometry"]

newdata.head()

# Check the area of polygon
print("Area: ", round(newdata.at[0, "geometry"].area, 6),"angulares")

newdata.plot()

# Re-project the data
newdata_3067 = newdata.to_crs(3067)

newdata_3067.head()

newdata_3067.plot()

# Check the area
print("Area: ", round(newdata_3067.at[0, "geometry"].area, 3),"m²")

# Save new file
fp = "/content/drive/MyDrive/Colab/L2_data/Senaatintori_3067.shp"
newdata_3067.to_file(fp)